[package]
name = "quicksort"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "quicksort"
path = "src/quicksort.rs"

[dependencies]
nix = { version = "0.29.0", features = ["signal", "process"] }
rand = "0.8" 

