[package]
name = "array_sum"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "array_sum"
path = "src/array_sum.rs"

[dependencies]
rand = "0.8"
libc = "=0.2.126"

[profile.dev]
overflow-checks = false
